# Dockerfile for Front-End (EC2)
FROM nginx:alpine

# Remove the default Nginx welcome page
RUN rm /usr/share/nginx/html/*

# Copy our front-end HTML file to the Nginx web directory
COPY index.html /usr/share/nginx/html/index.html
COPY uce-logo.png /usr/share/nginx/html/uce-logo.png

# Expose port 80 for the web server
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
